name: Python CI Pipeline

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        #make sure we have the latest pip version
        python -m pip install --upgrade pip
        # requirements for pyspelling
        apt-get update && apt-get -y install aspell aspell-en
        #install ruff and pyspelling
        pip install ruff pyspelling

    - name: Check Build
      run: |
        python -m compileall -q .

    - name: Lint with Ruff
      run: |
        ruff check .

    - name: Format Code
      run: |
        ruff format .

    - name: Spell Check
      run: |
        pyspelling
    - name: Push the reformated code
      run: |
        echo "to implement later: add, commit and push changes introduced by formatting step"

    - name: Cleanup
      if: always()
      run: echo "CI pipeline completed"
